//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reactchatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConnection
    {
        public int UserConnectionId { get; set; }
        public int UserId { get; set; }
        public int ChatroomId { get; set; }
    
        public virtual Chatroom Chatroom { get; set; }
        public virtual User User { get; set; }
    }
}
